notifications:
  slack: true
  email: true

addons:
  apt:
    packages:
      - libhdf5-serial-dev

sudo: false
language: python
python:
  - 2.7
  - 3.5
  - 3.6

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -U pip wheel
  - pip install -U Cython
  - pip install -U tox-travis tox

script:
  - tox
